<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="AutoMapper" />
		<PackageReference Include="MailKit" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
		<PackageReference Include="Microsoft.CodeAnalysis.Common" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
		<PackageReference Include="Microsoft.Extensions.Options" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="MimeKit" />
		<PackageReference Include="System.Text.Json" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\src\Modules\FengShui\FengShui.Domain\FengShui.Domain.csproj" />
		<ProjectReference Include="..\src\Shared\Shared.Infrastructure\Shared.Infrastructure.csproj" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\src\Shared\Shared.Kernel\Shared.Kernel.csproj" />
	</ItemGroup>
</Project>
