version: "3.8" # Changed from "4.34.3" to a more standard version
services:
  fengshuiapi:
    build: .
    ports:
      - "7285:7285"
    environment:
      - ASPNETCORE_URLS=https://+:7285
      - ASPNETCORE_HTTPS_PORT=7285
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=KoiFengShui;User Id=sa;Password=12345;TrustServerCertificate=true
    volumes:
      - ${APPDATA}/microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${USERPROFILE}/.aspnet/https:/root/.aspnet/https:ro
      - fengshuiapi-keys:/root/.aspnet/DataProtection-Keys
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  fengshuiapi-keys:
