<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FengShui.Application\FengShui.Application.csproj" />
    <ProjectReference Include="..\FengShui.Infrastructure\FengShui.Infrastructure.csproj" />
  </ItemGroup>
</Project>
