// <auto-generated />
using System;
using KoiFengShuiSystem.DataAccess.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KoiFengShuiSystem.DataAccess.Migrations
{
    [DbContext(typeof(KoiFengShuiContext))]
    [Migration("20260406065411_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ElementId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Wallet")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("AccountId");

                    b.HasIndex("ElementId");

                    b.HasIndex("RoleId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.Direction", b =>
                {
                    b.Property<int>("DirectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DirectionId"));

                    b.Property<string>("DirectionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DirectionId");

                    b.ToTable("Directions");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.Element", b =>
                {
                    b.Property<int>("ElementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ElementId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ElementName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LuckyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ElementId");

                    b.ToTable("Elements");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.FAQ", b =>
                {
                    b.Property<int>("FAQId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FAQId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("FAQId");

                    b.HasIndex("AccountId");

                    b.ToTable("FAQs");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.FengShuiDirection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DirectionId")
                        .HasColumnType("int");

                    b.Property<int>("ElementId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DirectionId");

                    b.HasIndex("ElementId");

                    b.ToTable("FengShuiDirections");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.FishPond", b =>
                {
                    b.Property<int>("PondId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PondId"));

                    b.Property<int>("DirectionPlacement")
                        .HasColumnType("int");

                    b.Property<int>("ShapeId")
                        .HasColumnType("int");

                    b.HasKey("PondId");

                    b.HasIndex("DirectionPlacement");

                    b.HasIndex("ShapeId");

                    b.ToTable("FishPonds");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.Follow", b =>
                {
                    b.Property<int>("FollowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FollowId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("FollowId");

                    b.HasIndex("AccountId");

                    b.HasIndex("PostId");

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ImageId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.KoiBreed", b =>
                {
                    b.Property<int>("BreedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BreedId"));

                    b.Property<string>("BreedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ElementId")
                        .HasColumnType("int");

                    b.HasKey("BreedId");

                    b.HasIndex("CountryId");

                    b.HasIndex("ElementId");

                    b.ToTable("KoiBreeds");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.ListingImage", b =>
                {
                    b.Property<int>("ListingImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListingImageId"));

                    b.Property<string>("ImageDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<int>("MarketListingId")
                        .HasColumnType("int");

                    b.HasKey("ListingImageId");

                    b.HasIndex("ImageId");

                    b.HasIndex("MarketListingId");

                    b.ToTable("ListingImages");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.MarketCategory", b =>
                {
                    b.Property<int>("Categoryid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Categoryid"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Categoryid");

                    b.ToTable("MarketCategories");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.MarketplaceListing", b =>
                {
                    b.Property<int>("ListingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListingId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ElementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TierId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ListingId");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ElementId");

                    b.HasIndex("TierId");

                    b.ToTable("MarketplaceListings");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ElementId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PostId");

                    b.HasIndex("AccountId");

                    b.HasIndex("ElementId");

                    b.HasIndex("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.PostCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PostType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PostCategories");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.PostImage", b =>
                {
                    b.Property<int>("PostImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostImageId"));

                    b.Property<string>("ImageDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("PostImageId");

                    b.HasIndex("ImageId");

                    b.HasIndex("PostId");

                    b.ToTable("PostImages");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.Recommendation", b =>
                {
                    b.Property<int>("RecommendationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecommendationId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("BreedId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PondId")
                        .HasColumnType("int");

                    b.HasKey("RecommendationId");

                    b.HasIndex("AccountId");

                    b.HasIndex("BreedId");

                    b.HasIndex("PondId");

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.ShapeCategory", b =>
                {
                    b.Property<int>("ShapeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShapeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ElementId")
                        .HasColumnType("int");

                    b.Property<string>("ShapeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ShapeId");

                    b.HasIndex("ElementId");

                    b.ToTable("ShapeCategories");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.SubcriptionTier", b =>
                {
                    b.Property<int>("TierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TierId"));

                    b.Property<string>("TierName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TierId");

                    b.ToTable("SubcriptionTiers");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.TrafficLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("bit");

                    b.Property<string>("RequestMethod")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("TrafficLogs");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("ListingId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TierId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ListingId");

                    b.HasIndex("TierId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.Account", b =>
                {
                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.Element", "Element")
                        .WithMany("Accounts")
                        .HasForeignKey("ElementId");

                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId");

                    b.Navigation("Element");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.FAQ", b =>
                {
                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.Account", "Account")
                        .WithMany("FAQs")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.FengShuiDirection", b =>
                {
                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.Direction", "Direction")
                        .WithMany("FengShuiDirections")
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.Element", "Element")
                        .WithMany("FengShuiDirections")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Direction");

                    b.Navigation("Element");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.FishPond", b =>
                {
                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.FengShuiDirection", "DirectionPlacementNavigation")
                        .WithMany("FishPonds")
                        .HasForeignKey("DirectionPlacement")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.ShapeCategory", "Shape")
                        .WithMany("FishPonds")
                        .HasForeignKey("ShapeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DirectionPlacementNavigation");

                    b.Navigation("Shape");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.Follow", b =>
                {
                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.Account", "Account")
                        .WithMany("Follows")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.Post", "Post")
                        .WithMany("Follows")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.KoiBreed", b =>
                {
                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.Country", "Country")
                        .WithMany("KoiBreeds")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.Element", "Element")
                        .WithMany("KoiBreeds")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Element");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.ListingImage", b =>
                {
                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.Image", "Image")
                        .WithMany("ListingImages")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.MarketplaceListing", "MarketListing")
                        .WithMany("ListingImages")
                        .HasForeignKey("MarketListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("MarketListing");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.MarketplaceListing", b =>
                {
                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.Account", "Account")
                        .WithMany("MarketplaceListings")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.MarketCategory", "Category")
                        .WithMany("MarketplaceListings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.Element", "Element")
                        .WithMany("MarketplaceListings")
                        .HasForeignKey("ElementId");

                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.SubcriptionTier", "Tier")
                        .WithMany("MarketplaceListings")
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("Element");

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.Post", b =>
                {
                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.Account", "Account")
                        .WithMany("Posts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.Element", "Element")
                        .WithMany("Posts")
                        .HasForeignKey("ElementId");

                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.PostCategory", "IdNavigation")
                        .WithMany("Posts")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Element");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.PostImage", b =>
                {
                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.Image", "Image")
                        .WithMany("PostImages")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.Post", "Post")
                        .WithMany("PostImages")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.Recommendation", b =>
                {
                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.Account", "Account")
                        .WithMany("Recommendations")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.KoiBreed", "Breed")
                        .WithMany("Recommendations")
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.FishPond", "Pond")
                        .WithMany("Recommendations")
                        .HasForeignKey("PondId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Breed");

                    b.Navigation("Pond");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.ShapeCategory", b =>
                {
                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.Element", "Element")
                        .WithMany("ShapeCategories")
                        .HasForeignKey("ElementId");

                    b.Navigation("Element");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.TrafficLog", b =>
                {
                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.Account", "Account")
                        .WithMany("TrafficLogs")
                        .HasForeignKey("AccountId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.Transaction", b =>
                {
                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.MarketplaceListing", "Listing")
                        .WithMany("Transactions")
                        .HasForeignKey("ListingId");

                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.SubcriptionTier", "Tier")
                        .WithMany("Transactions")
                        .HasForeignKey("TierId");

                    b.Navigation("Account");

                    b.Navigation("Listing");

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.Account", b =>
                {
                    b.Navigation("FAQs");

                    b.Navigation("Follows");

                    b.Navigation("MarketplaceListings");

                    b.Navigation("Posts");

                    b.Navigation("Recommendations");

                    b.Navigation("TrafficLogs");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.Country", b =>
                {
                    b.Navigation("KoiBreeds");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.Direction", b =>
                {
                    b.Navigation("FengShuiDirections");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.Element", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("FengShuiDirections");

                    b.Navigation("KoiBreeds");

                    b.Navigation("MarketplaceListings");

                    b.Navigation("Posts");

                    b.Navigation("ShapeCategories");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.FengShuiDirection", b =>
                {
                    b.Navigation("FishPonds");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.FishPond", b =>
                {
                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.Image", b =>
                {
                    b.Navigation("ListingImages");

                    b.Navigation("PostImages");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.KoiBreed", b =>
                {
                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.MarketCategory", b =>
                {
                    b.Navigation("MarketplaceListings");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.MarketplaceListing", b =>
                {
                    b.Navigation("ListingImages");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.Post", b =>
                {
                    b.Navigation("Follows");

                    b.Navigation("PostImages");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.PostCategory", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.ShapeCategory", b =>
                {
                    b.Navigation("FishPonds");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.SubcriptionTier", b =>
                {
                    b.Navigation("MarketplaceListings");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
