<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <UserSecretsId>605637f8-7a75-4e61-9cc8-1e4fb8f8b6ea</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\KoiFengShuiSystem.Api\KoiFengShuiSystem.Api.csproj" />
    <ProjectReference Include="..\Modules\Identity\Identity.Application\Identity.Application.csproj" />
    <ProjectReference Include="..\Modules\Identity\Identity.Api\Identity.Api.csproj" />
    <ProjectReference Include="..\Modules\Identity\Identity.Infrastructure\Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\KoiFengShuiSystem.Shared\KoiFengShuiSystem.Shared.csproj" />
    <ProjectReference Include="..\Shared\Shared.Kernel\Shared.Kernel.csproj" />
    <ProjectReference Include="..\Shared\Shared.Infrastructure\Shared.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\FengShui\FengShui.Application\FengShui.Application.csproj" />
    <ProjectReference Include="..\Modules\FengShui\FengShui.Infrastructure\FengShui.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\FengShui\FengShui.Api\FengShui.Api.csproj" />
    <ProjectReference Include="..\Modules\Community\Community.Application\Community.Application.csproj" />
    <ProjectReference Include="..\Modules\Community\Community.Infrastructure\Community.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Community\Community.Api\Community.Api.csproj" />
  </ItemGroup>

</Project>
