// <auto-generated />
using System;
using KoiFengShuiSystem.Shared.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Shared.Infrastructure.Migrations
{
    [DbContext(typeof(KoiFengShuiContext))]
    [Migration("20260822194203_ConsolidatedBaselinePostgreSql")]
    partial class ConsolidatedBaselinePostgreSql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.FAQ", b =>
                {
                    b.Property<int>("FAQId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FAQId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("FAQId");

                    b.HasIndex("AccountId");

                    b.ToTable("FAQs");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.Follow", b =>
                {
                    b.Property<int>("FollowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FollowId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.HasKey("FollowId");

                    b.HasIndex("AccountId");

                    b.HasIndex("PostId");

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ImageId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PostId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("ElementId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("PostId");

                    b.HasIndex("AccountId");

                    b.HasIndex("ElementId");

                    b.HasIndex("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.PostCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PostType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("PostCategories");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.PostImage", b =>
                {
                    b.Property<int>("PostImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PostImageId"));

                    b.Property<string>("ImageDescription")
                        .HasColumnType("text");

                    b.Property<int>("ImageId")
                        .HasColumnType("integer");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.HasKey("PostImageId");

                    b.HasIndex("ImageId");

                    b.HasIndex("PostId");

                    b.ToTable("PostImages");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.TrafficLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("boolean");

                    b.Property<string>("RequestMethod")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("TrafficLogs");
                });

            modelBuilder.Entity("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.Direction", b =>
                {
                    b.Property<int>("DirectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DirectionId"));

                    b.Property<string>("DirectionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("DirectionId");

                    b.ToTable("Directions");
                });

            modelBuilder.Entity("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.Element", b =>
                {
                    b.Property<int>("ElementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ElementId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ElementName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LuckyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ElementId");

                    b.ToTable("Elements");
                });

            modelBuilder.Entity("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.FengShuiDirection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DirectionId")
                        .HasColumnType("integer");

                    b.Property<int>("ElementId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DirectionId");

                    b.HasIndex("ElementId");

                    b.ToTable("FengShuiDirections");
                });

            modelBuilder.Entity("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.FishPond", b =>
                {
                    b.Property<int>("PondId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PondId"));

                    b.Property<int>("DirectionPlacement")
                        .HasColumnType("integer");

                    b.Property<int>("ShapeId")
                        .HasColumnType("integer");

                    b.HasKey("PondId");

                    b.HasIndex("DirectionPlacement");

                    b.HasIndex("ShapeId");

                    b.ToTable("FishPonds");
                });

            modelBuilder.Entity("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.KoiBreed", b =>
                {
                    b.Property<int>("BreedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BreedId"));

                    b.Property<string>("BreedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ElementId")
                        .HasColumnType("integer");

                    b.HasKey("BreedId");

                    b.HasIndex("CountryId");

                    b.HasIndex("ElementId");

                    b.ToTable("KoiBreeds");
                });

            modelBuilder.Entity("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.PartnerShop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("PartnerShops", (string)null);
                });

            modelBuilder.Entity("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.Recommendation", b =>
                {
                    b.Property<int>("RecommendationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecommendationId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<int>("BreedId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PondId")
                        .HasColumnType("integer");

                    b.HasKey("RecommendationId");

                    b.HasIndex("AccountId");

                    b.HasIndex("BreedId");

                    b.HasIndex("PondId");

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.ShapeCategory", b =>
                {
                    b.Property<int>("ShapeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShapeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ElementId")
                        .HasColumnType("integer");

                    b.Property<string>("ShapeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ShapeId");

                    b.HasIndex("ElementId");

                    b.ToTable("ShapeCategories");
                });

            modelBuilder.Entity("KoiFengShuiSystem.Modules.Identity.Domain.Entities.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountId"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ElementId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("ResetTokenExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ResetTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("AccountId");

                    b.HasIndex("ElementId");

                    b.HasIndex("RoleId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("KoiFengShuiSystem.Modules.Identity.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("KoiFengShuiSystem.Modules.Identity.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.FAQ", b =>
                {
                    b.HasOne("KoiFengShuiSystem.Modules.Identity.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.Follow", b =>
                {
                    b.HasOne("KoiFengShuiSystem.Modules.Identity.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.Post", "Post")
                        .WithMany("Follows")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.Post", b =>
                {
                    b.HasOne("KoiFengShuiSystem.Modules.Identity.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.Element", null)
                        .WithMany("Posts")
                        .HasForeignKey("ElementId");

                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.PostCategory", "IdNavigation")
                        .WithMany("Posts")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.PostImage", b =>
                {
                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.Image", "Image")
                        .WithMany("PostImages")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KoiFengShuiSystem.DataAccess.Models.Post", "Post")
                        .WithMany("PostImages")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.TrafficLog", b =>
                {
                    b.HasOne("KoiFengShuiSystem.Modules.Identity.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId");
                });

            modelBuilder.Entity("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.FengShuiDirection", b =>
                {
                    b.HasOne("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.Direction", "Direction")
                        .WithMany("FengShuiDirections")
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.Element", "Element")
                        .WithMany("FengShuiDirections")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Direction");

                    b.Navigation("Element");
                });

            modelBuilder.Entity("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.FishPond", b =>
                {
                    b.HasOne("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.FengShuiDirection", "DirectionPlacementNavigation")
                        .WithMany("FishPonds")
                        .HasForeignKey("DirectionPlacement")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.ShapeCategory", "Shape")
                        .WithMany("FishPonds")
                        .HasForeignKey("ShapeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DirectionPlacementNavigation");

                    b.Navigation("Shape");
                });

            modelBuilder.Entity("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.KoiBreed", b =>
                {
                    b.HasOne("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.Country", "Country")
                        .WithMany("KoiBreeds")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.Element", "Element")
                        .WithMany("KoiBreeds")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Element");
                });

            modelBuilder.Entity("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.Recommendation", b =>
                {
                    b.HasOne("KoiFengShuiSystem.Modules.Identity.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.KoiBreed", "Breed")
                        .WithMany("Recommendations")
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.FishPond", "Pond")
                        .WithMany("Recommendations")
                        .HasForeignKey("PondId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Breed");

                    b.Navigation("Pond");
                });

            modelBuilder.Entity("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.ShapeCategory", b =>
                {
                    b.HasOne("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.Element", "Element")
                        .WithMany("ShapeCategories")
                        .HasForeignKey("ElementId");

                    b.Navigation("Element");
                });

            modelBuilder.Entity("KoiFengShuiSystem.Modules.Identity.Domain.Entities.Account", b =>
                {
                    b.HasOne("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.Element", null)
                        .WithMany("Accounts")
                        .HasForeignKey("ElementId");

                    b.HasOne("KoiFengShuiSystem.Modules.Identity.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("KoiFengShuiSystem.Modules.Identity.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("KoiFengShuiSystem.Modules.Identity.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.Image", b =>
                {
                    b.Navigation("PostImages");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.Post", b =>
                {
                    b.Navigation("Follows");

                    b.Navigation("PostImages");
                });

            modelBuilder.Entity("KoiFengShuiSystem.DataAccess.Models.PostCategory", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.Country", b =>
                {
                    b.Navigation("KoiBreeds");
                });

            modelBuilder.Entity("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.Direction", b =>
                {
                    b.Navigation("FengShuiDirections");
                });

            modelBuilder.Entity("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.Element", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("FengShuiDirections");

                    b.Navigation("KoiBreeds");

                    b.Navigation("Posts");

                    b.Navigation("ShapeCategories");
                });

            modelBuilder.Entity("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.FengShuiDirection", b =>
                {
                    b.Navigation("FishPonds");
                });

            modelBuilder.Entity("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.FishPond", b =>
                {
                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.KoiBreed", b =>
                {
                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("KoiFengShuiSystem.Modules.FengShui.Domain.Entities.ShapeCategory", b =>
                {
                    b.Navigation("FishPonds");
                });
#pragma warning restore 612, 618
        }
    }
}
