// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace KoiFengShuiSystem.DataAccess.Models;

public partial class Account
{
    public int AccountId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    [DataType(DataType.Date)]
    public DateTime Dob { get; set; }

    public string Phone { get; set; }

    public string Gender { get; set; }

    public int? ElementId { get; set; }

    public int? RoleId { get; set; }

    public virtual Element Element { get; set; }

    public virtual ICollection<Follow> Follows { get; set; } = new List<Follow>();

    public virtual ICollection<MarketplaceListing> MarketplaceListings { get; set; } = new List<MarketplaceListing>();

    public virtual ICollection<Recommendation> Recommendations { get; set; } = new List<Recommendation>();

    public virtual Role Role { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();

    [JsonIgnore]
    public string? Password { get; set; }
}