// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiFengShuiSystem.DataAccess.Models;

public partial class CustomerFaP
{
    public int FapId { get; set; }

    public DateTime DoB { get; set; }

    public string Direction { get; set; }

    public string FishBreed { get; set; }

    public int FishQuantity { get; set; }

    public int ElementId { get; set; }

    public double Percentage { get; set; }

    public virtual Element Element { get; set; }
}