// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiFengShuiSystem.DataAccess.Models;

public partial class Element
{
    public int ElementId { get; set; }

    public string ElementName { get; set; }

    public string Description { get; set; }

    public string LuckyNumber { get; set; }

    public virtual ICollection<Account> Accounts { get; set; } = new List<Account>();

    public virtual ICollection<CustomerFaP> CustomerFaPs { get; set; } = new List<CustomerFaP>();

    public virtual ICollection<FengShuiDirection> FengShuiDirections { get; set; } = new List<FengShuiDirection>();

    public virtual ICollection<KoiBreed> KoiBreeds { get; set; } = new List<KoiBreed>();

    public virtual ICollection<MarketplaceListing> MarketplaceListings { get; set; } = new List<MarketplaceListing>();

    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();

    public virtual ICollection<ShapeCategory> ShapeCategories { get; set; } = new List<ShapeCategory>();
}