// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiFengShuiSystem.DataAccess.Models;

public partial class FengShuiDirection
{
    public int Id { get; set; }

    public int DirectionId { get; set; }

    public string Description { get; set; }

    public int ElementId { get; set; }

    public virtual Direction Direction { get; set; }

    public virtual Element Element { get; set; }

    public virtual ICollection<FishPond> FishPonds { get; set; } = new List<FishPond>();
}