// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiFengShuiSystem.DataAccess.Models;

public partial class FishPond
{
    public int PondId { get; set; }

    public int ShapeId { get; set; }

    public int DirectionPlacement { get; set; }

    public virtual FengShuiDirection DirectionPlacementNavigation { get; set; }

    public virtual ICollection<Recommendation> Recommendations { get; set; } = new List<Recommendation>();

    public virtual ShapeCategory Shape { get; set; }
}