// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiFengShuiSystem.DataAccess.Models;

public partial class Follow
{
    public int FollowId { get; set; }

    public int PostId { get; set; }

    public int AccountId { get; set; }

    public virtual Account Account { get; set; }

    public virtual Post Post { get; set; }
}