// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiFengShuiSystem.DataAccess.Models;

public partial class KoiBreed
{
    public int BreedId { get; set; }

    public int ElementId { get; set; }

    public int CountryId { get; set; }

    public string BreedName { get; set; }

    public string Color { get; set; }

    public string Description { get; set; }

    public virtual Country Country { get; set; }

    public virtual Element Element { get; set; }

    public virtual ICollection<Recommendation> Recommendations { get; set; } = new List<Recommendation>();
}