// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiFengShuiSystem.DataAccess.Models;

public partial class ListingImage
{
    public int ListingImageId { get; set; }

    public int MarketListingId { get; set; }

    public int ImageId { get; set; }

    public string ImageDescription { get; set; }

    public virtual Image Image { get; set; }

    public virtual MarketplaceListing MarketListing { get; set; }
}