// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiFengShuiSystem.DataAccess.Models;

public partial class MarketplaceListing
{
    public int ListingId { get; set; }

    public int AccountId { get; set; }

    public int TierId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public int Quantity { get; set; }

    public int CategoryId { get; set; }

    public DateTime CreateAt { get; set; }

    public DateTime ExpiresAt { get; set; }

    public bool IsActive { get; set; }

    public string Status { get; set; }

    public int? ElementId { get; set; }

    public virtual Account Account { get; set; }

    public virtual MarketCategory Category { get; set; }

    public virtual Element Element { get; set; }

    public virtual ICollection<ListingImage> ListingImages { get; set; } = new List<ListingImage>();

    public virtual SubcriptionTier Tier { get; set; }
}