// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiFengShuiSystem.DataAccess.Models;

public partial class PostImage
{
    public int PostImageId { get; set; }

    public int PostId { get; set; }

    public int ImageId { get; set; }

    public string ImageDescription { get; set; }

    public virtual Image Image { get; set; }

    public virtual Post Post { get; set; }
}