// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiFengShuiSystem.DataAccess.Models;

public partial class PostCategory
{
    public int Id { get; set; }

    public string PostType { get; set; }

    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();
}