// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiFengShuiSystem.DataAccess.Models;

public partial class Recommendation
{
    public int RecommendationId { get; set; }

    public int AccountId { get; set; }

    public int BreedId { get; set; }

    public int PondId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Account Account { get; set; }

    public virtual KoiBreed Breed { get; set; }

    public virtual FishPond Pond { get; set; }
}